version: '3'
services:
  server:
    container_name: server
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: "always"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: volume
        source: ./data/certbot/www
        target: /var/www/certbot
      - type: volume
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./nginx/conf.d/app.conf
        target: /etc/nginx/conf.d/app.conf
    depends_on:
      - "server"


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot