version: '3'
services:
  server:
    container_name: bookmark-server-container
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: "always"

  nginx:
    container_name: bookmark-nginx-container
    image: guseh08/bookmark-nginx-image
    ports:
      - 80:80
    depends_on:
      - "server"
