version: '3'
services:
  server:
    container_name: bookmark-server-container
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: "always"

  nginx:
    container_name: bookmark-nginx-container
    image: guseh08/bookmark-nginx-image
    restart: unless-stopped
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - "server"


  certbot:
    container_name: certbot_service
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot