version: '3'
services:
  server:
    container_name: server
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: "always"

  nginx:
    container_name: nginx
    image: guseh08/bookmark-nginx-image
    restart: unless-stopped
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/github/workspace/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/github/workspace/data/certbot/www:/var/www/certbot
      - /home/ubuntu/github/workspace/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - "server"


  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /home/ubuntu/github/workspace/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/github/workspace/data/certbot/www:/var/www/certbot