version: '3.9'
services:
  server:
    container_name: server
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: "always"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      # . : /home/ubuntu/github/workspace
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./conf/:/etc/nginx/conf.d
      #     - ./github/workspace/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - "server"


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot