version: '3.9'
services:
  server:
    container_name: server
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    environment:
      - "SPRING_PROFILES_ACTIVE=prod1"
    restart: "always"

  web:
    container_name: web
    image: guseh08/bookmark-web
    expose:
      - 5173

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    expose:
      - 80
      - 443
    volumes:
      # . : /home/ubuntu/github/workspace
      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/data/certbot/www:/var/www/certbot
      - /home/ubuntu/data/nginx/conf/:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "server"
      - "web"
    environment:
       TZ: "Asia/Seoul"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      API_URL: "https://bookmark-tool.com/docs/openapi3.yaml"
#      SWAGGER_JSON: "http://server:9090/docs/openapi3.yaml"
