version: '3'
services:
  server:
    container_name: server
    image: guseh08/bookmark-server-image
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: "always"

  nginx:
    container_name: nginx
    image: guseh08/bookmark-nginx-image
    restart: unless-stopped
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./github/workspace/data/conf/conf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./github/workspace/data/conf/conf:/etc/letsencrypt
      - ./github/workspace/data/certbot/www:/var/www/certbot
    depends_on:
      - "server"


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./github/workspace/data/conf/conf:/etc/letsencrypt
      - ./github/workspace/data/certbot/www:/var/www/certbot