FROM nginx
COPY ./nginx/conf.d/nginx.conf /etc/nginx/conf.d
COPY ./github/workspace/data/conf/conf/options-ssl-nginx.conf /etc/letsencrypt/options-ssl-nginx.conf
#COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d
#https://forums.docker.com/t/docker-error-parsing-config-error-21-is-a-directory-config-config-yml/115534/5