name: SpringBoot CICD with Gradle version 1.1.1

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  springboot-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: 11
            distribution: 'temurin'

      # Create application.properties
      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.properties
      - run: echo -e "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties
      - uses: actions/upload-artifact@v3
        with:
          name: application.properties
          path: ./src/main/resources/application.properties
          retention-days: 1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build SpringBoot Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookmark-server-image:latest
          no-cache: true

      - name : Build NginX Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookmark-nginx-image:latest
          no-cache: true

      - name: Copy docker-compose.yml to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          source: "/github/workspace/docker-compose.yaml"
          target: "/home/${{ secrets.VM_USERNAME }}/"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            if [ "$(docker ps -qa)" ]; then
              sudo docker rm -f $(docker ps -qa)
            fi
            sudo docker pull ${{ secrets.DOCKER_REPO }}/bookmark-server-image
            sudo docker pull ${{ secrets.DOCKER_REPO }}/bookmark-nginx-image
            sudo docker compose -f /home/ubuntu/github/workspace/docker-compose.yaml up -d
            docker image prune -a

      - name: Send Github Actions Result to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
